# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 19:17
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160510_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='showcase_box',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
