# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0003_auto_20150817_1256'),
        ('home', '0004_homepage_showcase_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='showcase_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_embed_videos.EmbedVideo', verbose_name='Video'),
        ),
    ]
