# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 21:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_showcase_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_card_carousel',
            field=wagtail.wagtailcore.fields.StreamField([('page_card_carousel', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock()), (b'text', wagtail.wagtailcore.blocks.RichTextBlock())])))], null=True),
        ),
    ]
