# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 05:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_page_card_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='page_card_carousel',
            field=wagtail.wagtailcore.fields.StreamField([('page_card_carousel', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock()), (b'text', wagtail.wagtailcore.blocks.RichTextBlock())])))], null=True),
        ),
    ]
