# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:32
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160713_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_card_rows',
            field=wagtail.wagtailcore.fields.StreamField([('page_card_block_row', wagtail.wagtailcore.blocks.StructBlock([(b'left', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock()), (b'text', wagtail.wagtailcore.blocks.RichTextBlock())])), (b'middle', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock()), (b'text', wagtail.wagtailcore.blocks.RichTextBlock())], required=False)), (b'right', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock()), (b'text', wagtail.wagtailcore.blocks.RichTextBlock())], required=False))]))], null=True),
        ),
    ]
