# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160713_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_card_rows',
            field=wagtail.wagtailcore.fields.StreamField([('page_card_block_row', wagtail.wagtailcore.blocks.StructBlock([(b'left', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), (b'heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'text', wagtail.wagtailcore.blocks.TextBlock(required=False))])), (b'middle', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), (b'heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'text', wagtail.wagtailcore.blocks.TextBlock(required=False))], required=False)), (b'right', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), (b'heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'text', wagtail.wagtailcore.blocks.TextBlock(required=False))], required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='page_card_carousel',
            field=wagtail.wagtailcore.fields.StreamField([('page_card_carousel', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'link', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), (b'heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'text', wagtail.wagtailcore.blocks.TextBlock(required=False))])))], null=True),
        ),
    ]
